import Foundation
import IMGLYEngine

@MainActor
func storeCustomMetadata(engine: Engine) async throws {
  // highlight-storeCustomMetadata-setup
  let scene = try engine.scene.create()

  let page = try engine.block.create(.page)
  try engine.block.setWidth(page, value: 800)
  try engine.block.setHeight(page, value: 600)
  try engine.block.appendChild(to: scene, child: page)

  let imageBlock = try engine.block.create(.graphic)
  try engine.block.setShape(imageBlock, shape: engine.block.createShape(.rect))
  try engine.block.setWidth(imageBlock, value: 400)
  try engine.block.setHeight(imageBlock, value: 300)
  try engine.block.setPositionX(imageBlock, value: 200)
  try engine.block.setPositionY(imageBlock, value: 150)

  let imageFill = try engine.block.createFill(.image)
  try engine.block.setString(
    imageFill,
    property: "fill/image/imageFileURI",
    value: "https://img.ly/static/ubq_samples/sample_1.jpg",
  )
  try engine.block.setFill(imageBlock, fill: imageFill)

  try engine.block.appendChild(to: page, child: imageBlock)
  // highlight-storeCustomMetadata-setup

  // highlight-storeCustomMetadata-setMetadata
  try engine.block.setMetadata(imageBlock, key: "externalId", value: "asset-12345")
  try engine.block.setMetadata(imageBlock, key: "source", value: "user-upload")
  try engine.block.setMetadata(imageBlock, key: "uploadedBy", value: "user@example.com")
  // highlight-storeCustomMetadata-setMetadata

  // highlight-storeCustomMetadata-getMetadata
  if try engine.block.hasMetadata(imageBlock, key: "externalId") {
    let externalId = try engine.block.getMetadata(imageBlock, key: "externalId")
    print("External ID:", externalId)
  }
  // highlight-storeCustomMetadata-getMetadata

  // highlight-storeCustomMetadata-findAllMetadata
  let allKeys = try engine.block.findAllMetadata(imageBlock)
  for key in allKeys {
    let value = try engine.block.getMetadata(imageBlock, key: key)
    print("\(key): \(value)")
  }
  // highlight-storeCustomMetadata-findAllMetadata

  // highlight-storeCustomMetadata-storeStructuredData
  struct GenerationInfo: Codable {
    let source: String
    let model: String
    let timestamp: Int64
  }

  let info = GenerationInfo(
    source: "ai-generated",
    model: "stable-diffusion",
    timestamp: Int64(Date().timeIntervalSince1970 * 1000),
  )
  let encoded = try JSONEncoder().encode(info)
  try engine.block.setMetadata(
    imageBlock,
    key: "generationInfo",
    value: String(data: encoded, encoding: .utf8)!,
  )

  let raw = try engine.block.getMetadata(imageBlock, key: "generationInfo")
  let decoded = try JSONDecoder().decode(GenerationInfo.self, from: Data(raw.utf8))
  print("Generated by \(decoded.model) at \(decoded.timestamp)")
  // highlight-storeCustomMetadata-storeStructuredData

  // highlight-storeCustomMetadata-removeMetadata
  if try engine.block.hasMetadata(imageBlock, key: "uploadedBy") {
    try engine.block.removeMetadata(imageBlock, key: "uploadedBy")
  }
  // highlight-storeCustomMetadata-removeMetadata

  // highlight-storeCustomMetadata-verifyRemoval
  let stillHasKey = try engine.block.hasMetadata(imageBlock, key: "uploadedBy")
  print("Has uploadedBy after removal:", stillHasKey)

  let remainingKeys = try engine.block.findAllMetadata(imageBlock)
  print("Remaining metadata keys:", remainingKeys)
  // highlight-storeCustomMetadata-verifyRemoval
}
